# Generated by Django 2.1.5 on 2022-04-06 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_currency'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
